{{- if .Values.enabled }}
{{- $domain := .Values.domain -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.global.development }}
        - name: streamplace
          hostPath:
            path: {{ .Values.global.rootDirectory }}
        - name: app
          hostPath:
            path: {{ .Values.global.rootDirectory }}/packages/{{ .Chart.Name }}
        - name: tmp
          emptyDir: {}
      {{- end }}
      {{- range .Values.developers}}
        - name: {{ .username }}
          secret:
            secretName: {{ .username }}.{{ $domain }}
      {{- end }}
        - name: wild-card
          secret:
            secretName: wild-card.{{ $domain }}
      containers:
      - name: {{ .Chart.Name }}
        {{- if .Values.global.development }}
        image: "{{ .Values.global.repo }}/{{ .Chart.Name }}:latest"
        command:
          - bash
          - -c
          - TMPDIR="/tmp" exec /app/node_modules/.bin/babel-watch -o '/app/src/*' /app/src/{{ .Chart.Name }}.js
        volumeMounts:
          - name: app
            mountPath: /app
          - name: streamplace
            mountPath: {{ .Values.global.rootDirectory }}
          - name: tmp
            mountPath: /tmp
        {{- else }}
        image: "{{ .Values.global.repo }}/{{ .Chart.Name }}:{{ .Chart.Version }}"
        {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        {{- if .Values.global.development }}
          - name: app
            mountPath: /app
          - name: streamplace
            mountPath: {{ .Values.global.rootDirectory }}
          - name: tmp
            mountPath: /tmp
        {{- end }}
        {{- range .Values.developers}}
          - name: {{ .username }}
            mountPath: /certs/{{ .username }}.{{ $domain }}
        {{- end}}
          - name: wild-card
            mountPath: /certs/wild-card.{{ $domain }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
{{- end }}
